# Generated by Django 4.2.7 on 2023-12-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_description_en',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='full_description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=155, null=True, unique=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, unique=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web_site.article', verbose_name='Статья'),
        ),
    ]
